"""
Pipeline run store — one folder per run, so a run can be stopped and resumed
later (even after a backend restart) and keeps a full history.

    uploads/pipeline_runs/<run_id>/
        run.json          manifest: config, per-step status, links to MiroFish
                          project/simulation/report ids (rewritten atomically)
        run.log           append-only JSON-lines event history (never rewritten)
        01_universe.json  step artifacts, one or more per step
        ...

Same persistence style as the original MiroFish (project.json / state.json /
progress.json): plain files, no database. A step only counts as completed once
its artifact is on disk, so resuming = skip every step whose status is
"completed".
"""

import json
import os
import threading
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from ..config import Config

PIPELINE_RUNS_DIR = os.path.join(Config.UPLOAD_FOLDER, 'pipeline_runs')

# Order matters: index + 1 == the step number the user refers to (1..8).
STEPS: List[Dict[str, str]] = [
    {"key": "universe", "title": "Ticker Universe"},
    {"key": "news", "title": "Finnhub News"},
    {"key": "seed", "title": "Reality Seed"},
    {"key": "prompt", "title": "Simulation Prompt"},
    {"key": "simulation", "title": "MiroFish Simulation"},
    {"key": "report_json", "title": "Report → JSON"},
    {"key": "consensus", "title": "Consensus"},
    {"key": "performance", "title": "Performance Report"},
]
STEP_KEYS = [s["key"] for s in STEPS]

STEP_PENDING = "pending"
STEP_RUNNING = "running"
STEP_COMPLETED = "completed"
STEP_FAILED = "failed"
STEP_PAUSED = "paused"          # stopped by the user; resumable

RUN_IN_PROGRESS = "in_progress"
RUN_COMPLETED = "completed"
RUN_FAILED = "failed"

_lock = threading.RLock()


class RunNotFoundError(KeyError):
    pass


def _now() -> str:
    return datetime.now().isoformat(timespec='seconds')


def _run_dir(run_id: str) -> str:
    # run ids are generated by us; reject anything path-like from the API
    if not run_id or os.sep in run_id or run_id.startswith('.'):
        raise RunNotFoundError(run_id)
    return os.path.join(PIPELINE_RUNS_DIR, run_id)


def _write_json_atomic(path: str, data: Any) -> None:
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    os.replace(tmp, path)


def create_run(name: str, config: Dict[str, Any]) -> Dict[str, Any]:
    run_id = f"run_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"
    now = _now()
    manifest = {
        "run_id": run_id,
        "name": name or run_id,
        "created_at": now,
        "updated_at": now,
        "status": RUN_IN_PROGRESS,
        "current_step": 1,
        "config": config,
        "steps": {
            s["key"]: {
                "index": i + 1,
                "title": s["title"],
                "status": STEP_PENDING,
                "started_at": None,
                "completed_at": None,
                "artifact": None,
                "summary": {},
                "error": None,
            }
            for i, s in enumerate(STEPS)
        },
        # filled by later steps (3-6) so a resumed run can find its MiroFish objects
        "links": {"project_id": None, "graph_id": None, "simulation_id": None, "report_id": None},
    }
    with _lock:
        os.makedirs(_run_dir(run_id), exist_ok=True)
        _write_json_atomic(os.path.join(_run_dir(run_id), 'run.json'), manifest)
    append_log(run_id, "run_created", f"Run '{manifest['name']}' created", {"config": config})
    return manifest


def load_run(run_id: str) -> Dict[str, Any]:
    path = os.path.join(_run_dir(run_id), 'run.json')
    if not os.path.exists(path):
        raise RunNotFoundError(run_id)
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_run(manifest: Dict[str, Any]) -> Dict[str, Any]:
    manifest["updated_at"] = _now()
    with _lock:
        _write_json_atomic(os.path.join(_run_dir(manifest["run_id"]), 'run.json'), manifest)
    return manifest


def list_runs() -> List[Dict[str, Any]]:
    if not os.path.isdir(PIPELINE_RUNS_DIR):
        return []
    runs = []
    for run_id in os.listdir(PIPELINE_RUNS_DIR):
        try:
            runs.append(load_run(run_id))
        except (RunNotFoundError, json.JSONDecodeError, OSError):
            continue
    runs.sort(key=lambda r: r.get("created_at", ""), reverse=True)
    return runs


def append_log(run_id: str, event: str, message: str, data: Optional[Dict[str, Any]] = None) -> None:
    line = {"time": _now(), "event": event, "message": message}
    if data:
        line["data"] = data
    with _lock:
        with open(os.path.join(_run_dir(run_id), 'run.log'), 'a', encoding='utf-8') as f:
            f.write(json.dumps(line, ensure_ascii=False) + "\n")


def read_log(run_id: str, limit: Optional[int] = None) -> List[Dict[str, Any]]:
    path = os.path.join(_run_dir(run_id), 'run.log')
    if not os.path.exists(path):
        return []
    with open(path, 'r', encoding='utf-8') as f:
        lines = [json.loads(l) for l in f if l.strip()]
    return lines[-limit:] if limit else lines


def write_artifact(run_id: str, filename: str, data: Any) -> str:
    path = os.path.join(_run_dir(run_id), filename)
    with _lock:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if isinstance(data, str):
            tmp = f"{path}.{os.getpid()}.tmp"
            with open(tmp, 'w', encoding='utf-8') as f:
                f.write(data)
            os.replace(tmp, path)
        else:
            _write_json_atomic(path, data)
    return filename


def read_artifact(run_id: str, filename: str) -> Any:
    path = os.path.join(_run_dir(run_id), filename)
    if not os.path.exists(path):
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f) if filename.endswith('.json') else f.read()


def patch_step(run_id: str, step_key: str, **fields: Any) -> Dict[str, Any]:
    """Update a step's fields (e.g. summary) without touching its status or the log."""
    with _lock:
        manifest = load_run(run_id)
        manifest["steps"][step_key].update(fields)
        return save_run(manifest)


def update_step(run_id: str, step_key: str, status: str, **fields: Any) -> Dict[str, Any]:
    """Set one step's status (+ artifact/summary/error) and keep run-level status in sync."""
    with _lock:
        manifest = load_run(run_id)
        step = manifest["steps"][step_key]
        step["status"] = status
        if status == STEP_RUNNING:
            step["started_at"] = _now()
            step["error"] = None
        elif status == STEP_COMPLETED:
            step["completed_at"] = _now()
            step["error"] = None
        step.update(fields)

        done = [k for k in STEP_KEYS if manifest["steps"][k]["status"] == STEP_COMPLETED]
        if len(done) == len(STEP_KEYS):
            manifest["status"] = RUN_COMPLETED
            manifest["current_step"] = len(STEP_KEYS)
        else:
            first_open = next(k for k in STEP_KEYS if manifest["steps"][k]["status"] != STEP_COMPLETED)
            manifest["current_step"] = manifest["steps"][first_open]["index"]
            manifest["status"] = RUN_FAILED if status == STEP_FAILED else RUN_IN_PROGRESS
        save_run(manifest)
    # no step number here: the UI merges some backend steps, so numbers would disagree
    append_log(run_id, f"step_{status}", f"{step['title']}: {status}",
               {"step": step_key, **({"error": fields["error"]} if fields.get("error") else {})})
    return manifest
