"""add universe and correlation graph tables

Revision ID: d3aa132579c4
Revises: 
Create Date: 2026-09-15 21:17:46.705069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3aa132579c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_clusters',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('stock_nodes',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['stock_clusters.cluster_id'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('correlation_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correlation_weight', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('PEARSON', 'SPEARMAN', name='correlationmethod'), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_ticker'], ['stock_nodes.ticker'], ),
    sa.ForeignKeyConstraint(['target_ticker'], ['stock_nodes.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correlation_edges')
    op.drop_table('stock_nodes')
    op.drop_table('stock_clusters')
    # ### end Alembic commands ###
